// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_MVC_Escola.web.Models;

namespace Projeto_MVC_Escola.web.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projeto_MVC_Escola.web.Data.Entities.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl");

                    b.Property<int?>("TurmaId");

                    b.Property<string>("cc");

                    b.Property<string>("contacto");

                    b.Property<int>("cp_1");

                    b.Property<int>("cp_2");

                    b.Property<string>("email");

                    b.Property<string>("genero");

                    b.Property<int>("id_turma");

                    b.Property<int>("localidade");

                    b.Property<int>("morada");

                    b.Property<string>("nif");

                    b.Property<string>("nome");

                    b.HasKey("Id");

                    b.HasIndex("TurmaId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Projeto_MVC_Escola.web.Data.Entities.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CursoId");

                    b.Property<int?>("ProfessorId");

                    b.Property<string>("area_formação");

                    b.Property<DateTime>("carga_horaria_discplina");

                    b.Property<DateTime>("creditos_discplina");

                    b.Property<int>("id_curso");

                    b.Property<int>("id_professor");

                    b.Property<string>("nome_disciplina");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Disciplina");
                });

            modelBuilder.Entity("Projeto_MVC_Escola.web.Data.Entities.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl");

                    b.Property<string>("cc");

                    b.Property<string>("contacto");

                    b.Property<int>("cp_1");

                    b.Property<int>("cp_2");

                    b.Property<string>("email");

                    b.Property<string>("genero");

                    b.Property<int>("localidade");

                    b.Property<int>("morada");

                    b.Property<string>("nif");

                    b.Property<string>("nome");

                    b.HasKey("Id");

                    b.ToTable("Professor");
                });

            modelBuilder.Entity("Projeto_MVC_Escola.web.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("carga_horaria_curso");

                    b.Property<DateTime>("data_fim");

                    b.Property<DateTime>("data_inicio");

                    b.Property<string>("nome_curso");

                    b.HasKey("Id");

                    b.ToTable("Curso");
                });

            modelBuilder.Entity("Projeto_MVC_Escola.web.Models.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CursoId");

                    b.Property<int>("id_curso");

                    b.Property<string>("nome_turma");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("Projeto_MVC_Escola.web.Data.Entities.Aluno", b =>
                {
                    b.HasOne("Projeto_MVC_Escola.web.Models.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId");
                });

            modelBuilder.Entity("Projeto_MVC_Escola.web.Data.Entities.Disciplina", b =>
                {
                    b.HasOne("Projeto_MVC_Escola.web.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId");

                    b.HasOne("Projeto_MVC_Escola.web.Data.Entities.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId");
                });

            modelBuilder.Entity("Projeto_MVC_Escola.web.Models.Turma", b =>
                {
                    b.HasOne("Projeto_MVC_Escola.web.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId");
                });
#pragma warning restore 612, 618
        }
    }
}
